INSERT INTO CAR (MODEL_NAME, MAKE, MODEL_YEAR, MILEAGE) VALUES ('BMW', 'Serie 1', 2020, 1000);
INSERT INTO CAR (MODEL_NAME, MAKE, MODEL_YEAR, MILEAGE) VALUES ('Toyota', 'Auris', 2019, 15000);
INSERT INTO CAR (MODEL_NAME, MAKE, MODEL_YEAR, MILEAGE) VALUES ('Renault', 'Megane', 2015, 500);