CREATE TABLE Car (
  REGISTRATION_NUMBER int(11) NOT NULL AUTO_INCREMENT,
  MODEL_NAME varchar(45) NOT NULL,
  MAKE varchar(45) NOT NULL,
  MODEL_YEAR int(4) NOT NULL,
  MILEAGE int(12) NOT NULL,
  PRIMARY KEY (REGISTRATION_NUMBER)
);
