CREATE TABLE CAR_CATEG
( CATEGORY_NAME VARCHAR(25) NOT NULL,
  NO_OF_LUGGAGE INTEGER NOT NULL,
  NO_OF_PERSON INTEGER NOT NULL,
  COST_PER_DAY NUMERIC(5,2) NOT NULL,
  LATE_FEE_PER_HOUR NUMERIC(5,2) NOT NULL,

  CONSTRAINT CARCATEGORYPK
  PRIMARY KEY (CATEGORY_NAME)
);

CREATE TABLE LOCATION_DETAILS
( LOCATION_ID CHAR(4) NOT NULL,
  LOCATION_NAME VARCHAR(50) NOT NULL,
  STREET VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  STATE_NAME VARCHAR(20) NOT NULL,
  ZIPCODE NUMERIC(5) NOT NULL,

  CONSTRAINT LOCATIONPK
  PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE CAR (
  REGISTRATION_NUMBER varchar(10) NOT NULL,
  MODEL_NAME varchar(45) NOT NULL,
  MAKE varchar(45) NOT NULL,
  MODEL_YEAR int(4) NOT NULL,
  MILEAGE int(12) NOT NULL,
  CAR_CATEGORY_NAME VARCHAR(25) NOT NULL,
  LOC_ID CHAR(4) NOT NULL,
  AVAILABILITY_FLAG CHAR(1) NOT NULL,

  CONSTRAINT CARPK
  PRIMARY KEY (REGISTRATION_NUMBER),

  CONSTRAINT CARFK1
  FOREIGN KEY (CAR_CATEGORY_NAME) REFERENCES CAR_CATEG(CATEGORY_NAME),

  CONSTRAINT CARFK2
  FOREIGN KEY (LOC_ID) REFERENCES LOCATION_DETAILS(LOCATION_ID)
);
